;(setq debug-on-error t)

(set-language-environment  'Japanese)
;(prefer-coding-system 'utf-8)
;(set-default-coding-systems 'utf-8-unix)

(global-hl-line-mode nil)
(show-paren-mode 1)
(display-time)
(line-number-mode t)
(column-number-mode t)
(transient-mark-mode 1)
(defalias 'yes-or-no-p 'y-or-n-p)
(if (fboundp 'scroll-bar-mode) (scroll-bar-mode -1))
(if (fboundp 'tool-bar-mode) (tool-bar-mode -1))
(setq make-backup-files nil)
(setq auto-save-default nil)
(setq inhibit-startup-message t)
(setq ns-command-modifier (quote meta))
(setq ns-alternate-modifier (quote super))
(set-frame-parameter (selected-frame) 'alpha '(90 50))
(setq scroll-step 1)

; gui only  C-: C-; C-@  C-, C-.
;           C-l  C-] C-z C-t
(define-key global-map (kbd "C-t") 'other-window)
(define-key global-map (kbd "C-h") 'delete-backward-char)
(define-key global-map (kbd "M-?") 'help-for-help)
(define-key global-map (kbd "C-z") 'undo)
(define-key global-map (kbd "C-c i") 'indent-region)
(define-key global-map (kbd "C-c C-i") 'hippie-expand)
(define-key global-map (kbd "C-c ;") 'comment-dwim)
(define-key global-map (kbd "M-C-g") 'grep)
(define-key global-map (kbd "C-[ M-C-g") 'goto-line)
(define-key global-map (kbd "C-x C-m") 'execute-extended-command)
(define-key global-map (kbd "C-c C-m") 'execute-extended-command)
(define-key global-map (kbd "C-w") 'backward-kill-word)
(define-key global-map (kbd "C-x C-k") 'kill-region)
(define-key global-map (kbd "C-c C-k") 'kill-region)
(global-unset-key (kbd "C-x m"))

